### ISSUE TITLE
一些error

### ISSUE THREAD

**Issue by Mizeron** [LordPenguin666/XTool#1]
系统发行版 debian
预备执行安装%!v(MISSING)
正在安装 Caddy
执行命令 sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
{"level":"ERROR","ts":"2023-03-04T07:46:48.662-0500","caller":"xray-tool/caddy_install.go:143","msg":"exit status 127"}
执行命令 curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
{"level":"ERROR","ts":"2023-03-04T07:46:48.990-0500","caller":"xray-tool/caddy_install.go:143","msg":"exit status 127"}
执行命令 curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
{"level":"ERROR","ts":"2023-03-04T07:46:49.563-0500","caller":"xray-tool/caddy_install.go:143","msg":"exit status 127"}
执行命令 sudo apt update -y
{"level":"ERROR","ts":"2023-03-04T07:46:49.579-0500","caller":"xray-tool/caddy_install.go:143","msg":"exit status 127"}
执行命令 sudo apt -y install caddy -y
{"level":"ERROR","ts":"2023-03-04T07:46:49.587-0500","caller":"xray-tool/caddy_install.go:143","msg":"exit status 127"}
{"level":"ERROR","ts":"2023-03-04T07:46:49.602-0500","caller":"xray-tool/caddy_operation.go:26","msg":"exit status 5"}
正在替换原版 Caddy
{"level":"ERROR","ts":"2023-03-04T07:46:51.419-0500","caller":"xray-tool/caddy_config.go:33","msg":"exit status 1"}
{"level":"ERROR","ts":"2023-03-04T07:46:51.419-0500","caller":"xray-tool/caddy_config.go:61","msg":"open /etc/caddy/Caddyfile: no such file or directory"}
{"level":"ERROR","ts":"2023-03-04T07:46:51.439-0500","caller":"xray-tool/caddy_operation.go:18","msg":"exit status 5"}
{"level":"ERROR","ts":"2023-03-04T07:46:51.454-0500","caller":"xray-tool/caddy_operation.go:34","msg":"exit status 1"}
等待 Caddy 申请证书中...
[Warning] 没有找到 SSL 证书, 请确认域名是否正确解析, 对应的端口是否开放, 在确认无误后请提交 issue!

**Comment by LordPenguin666** [comment]
看起来是 caddy 没有被正确安装, 请提供系统版本以及架构等等

**Comment by Mizeron** [comment]
> 

用的是moeclub脚本dd的debian10 64位 x86

**Comment by LordPenguin666** [comment]
https://github.com/LordPenguin666/XTool/commit/e6d2eb3d9add7411d94aed6c47fbc6f2f7598b32
