### ISSUE TITLE
ubuntu22.04 aarch64架构Caddy无法运行

### ISSUE THREAD

**Issue by myleo1** [LordPenguin666/XTool#7]
caddy无法正常运行导致证书无法申请，以及xray config.json无法生成。

caddy报错信息：

Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:4 - Error during parsing: getting module named 'caddy.listeners.proxy_protocol': module not registered: caddy.listeners.proxy_protocol

不知道为什么和amd64架构不同，caddy.listeners.proxy_protocol模块没有自动装上。
手动安装caddy也是如此

**Comment by LordPenguin666** [comment]
应该是下载 arm64 版本的 Caddy 时没有成功，尝试下手动替换掉原版 Caddy

https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com%2Fmastercactapus%2Fcaddy2-proxyprotocol

**Comment by myleo1** [comment]
是的，在arm64（我这边的ubuntu 22.04 aarch64）下，从apt源安装的caddy没有caddy.listeners.proxy_protocol，下载上面链接的就可以了。（其他系统未测试）
